from transformers import AutoConfig, AutoModel, AutoModelForTokenClassification, \
    AutoModelForQuestionAnswering, AutoModelForSequenceClassification, AutoTokenizer
from transformers.convert_slow_tokenizer import SLOW_TO_FAST_CONVERTERS, RobertaConverter

from .configuration_layoutlmv3 import Publaynet_LayoutLMv3Config
from .modeling_layoutlmv3 import (
    LayoutLMv3ForTokenClassification,
    LayoutLMv3ForQuestionAnswering,
    LayoutLMv3ForSequenceClassification,
    Publaynet_LayoutLMv3Model,
)
from .tokenization_layoutlmv3 import Publaynet_LayoutLMv3Tokenizer
from .tokenization_layoutlmv3_fast import Publaynet_LayoutLMv3TokenizerFast


AutoConfig.register("[publaynet_layoutlmv3", Publaynet_LayoutLMv3Config)
AutoModel.register(Publaynet_LayoutLMv3Config, Publaynet_LayoutLMv3Model)
AutoModelForTokenClassification.register(Publaynet_LayoutLMv3Config, LayoutLMv3ForTokenClassification)
AutoModelForQuestionAnswering.register(Publaynet_LayoutLMv3Config, LayoutLMv3ForQuestionAnswering)
AutoModelForSequenceClassification.register(Publaynet_LayoutLMv3Config, LayoutLMv3ForSequenceClassification)
AutoTokenizer.register(
    Publaynet_LayoutLMv3Config, slow_tokenizer_class=Publaynet_LayoutLMv3Tokenizer, fast_tokenizer_class=Publaynet_LayoutLMv3TokenizerFast
)
SLOW_TO_FAST_CONVERTERS.update({"Publaynet_LayoutLMv3Tokenizer": RobertaConverter})
